apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  volumeName: media-nfs-pv
  resources:
    requests:
      storage: 8.2T
