apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
