apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
  labels:
    app.kubernetes.io/part-of: media-stack
spec:
  capacity:
    storage: 8.2T
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
  nfs:
    server: 192.168.1.32
    path: /var/nfs/shared/media
    readOnly: false
