apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: media
  labels:
    app.kubernetes.io/part-of: media-stack
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  volumeName: media-nfs-pv
  resources:
    requests:
      storage: 8.2T
