apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config
  labels:
    app.kubernetes.io/name: seerr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
