{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "transmission-rpc",
    "namespace": "media",
    "annotations": {
      "argocd.argoproj.io/sync-options": "Prune=confirm,Delete=confirm"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "transmission-rpc",
        "namespace": "media",
        "annotations": {
          "sealedsecrets.bitnami.com/managed": "true"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "password": "AgAxvNhk1u/GW27WkNkXcRNk8+nj7f8pLR1sx3l68YNRRnMPTKpPKeyYrtB6eKL/rdtQ2q7hAqKvlZ0WpT8pIUAV9PmvaNA7np8baSsaAel1kQo8Im774fGd/OfZsquW4BWgpfsSHVRyOzH/ODM2BjZs67O8RG+ksGNCcdu75lPwgX3u9bHlLBrDR5LIojuUrgnH+1BlmmMHQRnLK2Frw8MjLiQ3nL1p/oMaYoiN6HNWixEZk3mJpOGEpUsQ3fhdX9+ZXuCuNOjvNVSSTqPbg1ewHFtyrGokQPlhPpfT29td5sgift0CQd6eHS2aqohnLwTdQSWhObuTcJKOPrOEtYXzbnwMIpxrjyv7VtH402p/n8IUmOmEvAaju2w055FXLHXRhH7nCJK2YUAUzpaXZt6xpjC1aCjLeANEOHIkm6dMOs7+WwXQW+EdvzKKag4DWuRb1hznHvxOo8NIixJH5d8+6/ZAhSqYMsbto3LATapOfhyIKYbGdfiH+q5mbTMacrHGechu9QrTymO8HQocziwR1O0guWp0C4H2zT47OmmNBSSkrXuVNjYrbwpIydkI7QPRZ1W6QBk8qIxiWWQqZeG8CTy8tn2PW+nrGRfl0MJMjwG9ReqIGzX2B0Ko+nli1twwuWecvnO8ydDtzaemNEujQNo2BEoNNHI+sAYS4azOUOF7iQdVRbY9vohUnQ5WdQ2Mq3twpvI=",
      "username": "AgBxpg88G+sInWjv9V1oyvQVa9zWWwp6sUdFIfzWvGug1P0BoEQguPVr2GV0MFv29i9l9oDfBbCYgln+kcb0ddTAchc/hKVNkvoyTCEf+235u8xVQh6rjfFCgMv/Vx5T7oBMQcFjwRhQQ2iHTJzXUvItIdKVJjo2Psl21k1hYRKwzHP1lZrAoMMPvlH+RopFu0xP4zmQJDSHSm7B5ecZYQG9iXeosixf7pTqdHc3Pm3yQyFGumBSrsrCtz5zNoRmK3jgu6g4mhOU4f9mP5Wmg3rubNXF6vm+dg/vYf5fLE+NoRKym+gVq8uXLiapDeNllP9P4wYhSS/LXdwwvo/+y6M3KY5M32+SsLlLi5DNK6m1QPugsTN5b7IuxHFhavk3TM2RORYG+O5++pTIIIRSWWkJVSf0465+Ekz11u5Kez+zxXE1t01an8LwZKKlC0o4OfBKoAIZwbmppHMxJWsSUoYnmdh0t62gYvkZEOWgaxCqLEgPWj1wIot7ekFh8br+w6GOGa2BXTvJDXLv1ljWipgZQEaIX4x3LUwrROgUji9Mc+mXISBH4sA5cflo390dlI2ccK/zgi41PqVgwoKBXIqEXZke/vM45qbFS0B0ayy9eA7U0OwfQtGB9zcN+lRsknyTdyyl8A9FezUFSOAXyzMAevlGB0zTaHZbZrAy/2XZPYB3jTtUBmkJnanUvB4MBlfLIxHyEuM="
    }
  }
}
